version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
